import { useBlockProps, RichText } from '@wordpress/block-editor';

export default function Save({ attributes }) {
    const { heroTitle, mainContent } = attributes;
    const assetsUrl = window.ashtechBlocksData ? window.ashtechBlocksData.assetsUrl : 'assets/';

    return (
        <div {...useBlockProps.save()}>
            {/* Hero Banner Section */}
            <section className="project-hero contactbg">
                <div className="project-hero__overlay"></div>
                <div className="project-hero__content">
                    <RichText.Content 
                        tagName="h1" 
                        className="project-hero__title" 
                        value={heroTitle} 
                    />
                </div>
            </section>

            {/* Privacy Policy Content */}
            <section className="privacy-policy">
                <div className="privacy-policy__container">
                    <p className="privacy-policy__updated">Last updated: July 23, 2021</p>

                    <div className="privacy-policy__intro">
                        <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
                        <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.</p>
                    </div>

                    <div className="privacy-policy__section">
                        <h2 className="privacy-policy__heading">Interpretation and Definitions</h2>
                        
                        <h3 className="privacy-policy__subheading">Interpretation</h3>
                        <p>The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>

                        <h3 className="privacy-policy__subheading">Definitions</h3>
                        <p>For the purposes of this Privacy Policy:</p>
                        <ul className="privacy-policy__list">
                            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
                            <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to ASHRAE Example Chapter, 180 Technology Parkway, Peachtree Corners, Georgia 30092.</li>
                            <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
                            <li><strong>Country</strong> refers to: Georgia, United States</li>
                            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
                            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
                            <li><strong>Service</strong> refers to the Website.</li>
                            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
                        </ul>
                    </div>

                    <div className="privacy-policy__section">
                        <h2 className="privacy-policy__heading">Collecting and Using Your Personal Data</h2>
                        
                        <h3 className="privacy-policy__subheading">Types of Data Collected</h3>
                        
                        <h4 className="privacy-policy__subheading-small">Personal Data</h4>
                        <p>While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
                        <ul className="privacy-policy__list">
                            <li>Email address</li>
                            <li>First name and last name</li>
                            <li>Phone number</li>
                            <li>Usage Data</li>
                        </ul>

                        <h4 className="privacy-policy__subheading-small">Usage Data</h4>
                        <p>Usage Data is collected automatically when using the Service.</p>
                        <p>Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.</p>
                    </div>

                    <div className="privacy-policy__section">
                        <h3 className="privacy-policy__subheading">Use of Your Personal Data</h3>
                        <p>The Company may use Personal Data for the following purposes:</p>
                        <ul className="privacy-policy__list">
                            <li><strong>To provide and maintain our Service,</strong> including to monitor the usage of our Service.</li>
                            <li><strong>To manage Your Account:</strong> to manage Your registration as a user of the Service.</li>
                            <li><strong>For the performance of a contract:</strong> the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.</li>
                            <li><strong>To contact You:</strong> To contact You by email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
                        </ul>
                    </div>

                    <div className="privacy-policy__section">
                        <h3 className="privacy-policy__subheading">Retention of Your Personal Data</h3>
                        <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy.</p>
                    </div>

                    <div className="privacy-policy__section">
                        <h3 className="privacy-policy__subheading">Security of Your Personal Data</h3>
                        <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure.</p>
                    </div>

                    <div className="privacy-policy__section">
                        <h2 className="privacy-policy__heading">Contact Us</h2>
                        <p>If you have any questions about this Privacy Policy, You can contact us:</p>
                        <ul className="privacy-policy__list privacy-policy__list--contact">
                            <li>By email: <a href="mailto:info@ashrae.org">info@ashrae.org</a></li>
                            <li>By phone number: <a href="tel:8005274723">800-527-4723</a></li>
                        </ul>
                    </div>

                    <RichText.Content 
                        tagName="div" 
                        className="privacy-policy__custom-content" 
                        value={mainContent} 
                    />
                </div>
            </section>
        </div>
    );
}
